version: '2'
services:
  ddexweb-app:
    image: ddexweb
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ddexweb-postgresql:5432/ddexweb
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://ddexweb-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://ddexweb-elasticsearch:9200
    ports:
      - 8080:8080
  ddexweb-postgresql:
    extends:
      file: postgresql.yml
      service: ddexweb-postgresql
  ddexweb-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: ddexweb-elasticsearch
